- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user # user is varibale is here
  
  - name: print varible value
    ansible.builtin.debug:
      msg: "user output is {{user}}"