- name: checking data types
  hosts: localhost
  vars:
    NAME: sivakumar #key value
    Skills:
    - Devops
    - shell
    - ansible #this how we give list of values in ansible
    - linux
    Experience:
      Devops: 7
      AWS: 1   # these are called map of values
      Docker: 2
    Traniner: true # boolean type
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name {{NAME}}"
      msg: "name {{Skills}}"
      msg: "name {{Experience}}"
      msg: "name {{Traniner}}"

  #- name: print LIST of values
    #ansible.builtin.debug:
      #msg: "name {{Skills}}"

  #- name: print maps
    #ansible.builtin.debug:
      #msg: "name {{Experience}}"

  #- name: print BOOLEAN
    #ansible.builtin.debug:
      #msg: "name {{Traniner}}"

