- name: loops
  hosts: localhost
  tasks:
  - name: print persons
    ansible.builtin.package:
      msg: "hello {{item}}"
      state: present
    loop:
    - git
    - mysql
    - nginx
    - postfix